---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: Faltan los dos puntos
  checked: true
- value: Falta la sangría
  checked: false
- value: El nombre de la función es poco descriptivo
  checked: false
- value: El nombre de función no respeta las convenciones de Python
  checked: false
- value: La función no retorna nada
  checked: true
- value: El nombre de los parámetros no son descriptivos
  checked: false
- value: Usa parámetros no definidos previamente
  checked: true
- value: El número se debería escribir 0,21
  checked: false
- value: No posee ningún error
  checked: false
name: "¿Iba el IVA?"
