---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`pocos_regalos(1,15)` devuelve `False`"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`pocos_regalos(1,15)` devuelve `0`"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`pocos_regalos(1)` devuelve `True`"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`pocos_regalos(1)` da un error"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`pocos_regalos(12,25)` devuelve `True`"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`pocos_regalos(301,15)` devuelve `False`"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`pocos_regalos(301,15)` da error"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '`pocos_regalos("1","1")` devuelve `True`'
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '`pocos_regalos("1","1")` devuelve `False`'
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '`pocos_regalos("1","1")` da error'
  checked: false
name: De capricornio
