---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: La función debe tener dos parámetros
  checked: false
- value: La función debe tener un parámetro
  checked: true
- value: La función debe devolver un string
  checked: false
- value: La función debe devolver un booleano
  checked: true
- value: La función debe devolver un Int
  checked: false
name: Necesito vacaciones
